uclaacm/teach-la-go-backend

lib/constants.go, lib/programManagement.go, lib/userManagement.go, middleware/logRequest.go, tools/log/log.go, tools/requests/requestTools.go
=> Fix package name bug

hooks/pre-commit, server.go
Sorry for the slow turnaround. Thoughts/suggestions?
I made it a loose requirement to pass govet and golint; if these commands raise an error, I just prompt the user to either enter Y to continue or N to abort.
=> Adding govet, golint, fixing gofmt

middleware/cors.go, server.go
- Small refactor of CORS middleware
=> Refactor and Apply CORS middleware

db/classManagement.go, db/db.go
I don't really have a method of testing how this affects Firebase, but it at least compiles and runs
- Wrapped DB operations in transactions
- Add a bit more error handling
=> Wrap firebase operations in transactions

db/constants.go
Required for https://github.com/uclaacm/TeachLAFrontend/pull/377 to work.
=> Add react to supported languages

db/class.go
Add getting ProgramData to GetClass
Closes #26
=> Get class programs

db/program.go, db/program_test.go, db/user.go
- Associate a program with a class in CreateProgram if wid is provided
- Delete a program from its associated class in DeleteProgram
=> Add associating programs with classes

db/collab.go, go.mod, go.sum, server.go
- Add CreateCollab endpoint
- Right now, it doesn't do much except die, but it should work as intended w/ future additions
=> Add CreateCollab

db/collab.go, server.go
=> Add JoinCollab endpoint

db/collab.go
Add name field and returns `400 Bad Request` if a session with that name exists.
Closes #33.
=> CreateCollab Extensions

db/class_test.go, db/program_test.go
There was a bug in our `AddToClass` test that was failing our GitHub actions on push. This PR will track fixing the test.
=> Fix AddToClass test.

db/class.go, db/program.go, db/user.go
There were some concerns of backend speed raised from our teaching team. In response to this, I have removed firestore transactions from our `GET`-like requests. This means that `GetClass`, `GetProgram`, and `GetUser` have been modified to use standard firestore operations rather than transactions to speed up their behavior.
Another modification made to improve speed is ignoring of failed child item retrievals. Where the old backend would enforce its retrievals succeeded, the backend in this PR is tolerant of programs missing, choosing the skip over them instead. A future consideration in this PR is to include missing program errors in the response.
No update to the docs needs to be made.
=> Remove transaction precondition for GET requests.

db/collab.go
Implements #42. Adds concept of ownership of a session. Right now, ownership does nothing but will be needed in the future.
=> add concept of a session's Teacher

db/class.go
=> Change JoinClass to take CID instead of WID

db/collab.go, db/constants.go
- Add read message handling
- Sends all other messages to connections which are "reading" from the source (currently only the teacher)
- Updates will be handled and sent to the recipient separately
=> add READ message handling

db/class_test.go, db/collab.go, db/program_test.go
adds more tests to TestUpdateProgram and adds golint format recommendations
=> Jon/test-update-program 

db/user.go
=> feat: add dev account field to user struct

db/collab.go
What it says on the tin. A bit nitpicky, but refactors `collab.go` so that we use `sync.Map` instead of a `map[string]Session` and `sync.Mutex` pair, and lets `Session` embed `sync.Mutex` so that we can lock it via `Session.Lock()` rather than `Session.Lock.Lock()`.
We use a `sync.Map` since it is specialized for high-read, low-write environments, amortizing to constant-time access. See the [sync package documentation](https://golang.org/pkg/sync/#Map).
=> Refactor collab.go to use sync.Map. Session embeds sync.Mutex.

db/class.go
Quick fix to add firestore annotations to class object
=> add firestore annotations

handler/class.go, handler/class_test.go
Allows students to fetch with user data, and receive instructor data
=> make getClass more lenient

db/db.go, db/mock.go, db/mock_test.go, db/tladb.go, handler/user.go
Finished tests for program, class, and user in mock_test.go for the mock.go methods.
=> MockDB Function Tests

handler/class.go, handler/class_test.go
=> Change JoinClass to use WID instead of CID

handler/program.go
There were some inconsistencies with the behavior of creating a program that began during refactor processes. This PR fixes:
- Associating programs with users on creation
- Populating default fields
=> Fix program creation
